name: 'Setup Node.js Environment'
description: 'Sets up the Node.js environment using actions/setup-node'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.4.0
      with:
        node-version: ${{ inputs.node-version }}
