/* Generated by ./script/iconify.js */
/* eslint-disable */
import React from 'react'
import PropTypes from 'prop-types'
import IconBase from './IconBase'
import classnames from 'classnames'

const IconChevron = ({ className, ...rest }) => {
  const classes = classnames(
    'icon',
    'icon--chevron',
    className,
  )

  return (
    <IconBase className={classes} xmlns="http://www.w3.org/2000/svg" viewBox="0 0 6 8"{...rest}><path className="path1" fill="none" fillRule="evenodd" stroke="#888" d="M1 0l4 4-4 4"/></IconBase>
  )
}

IconChevron.propTypes = {
  className: PropTypes.string,
}

export default IconChevron
/* eslint-enable */
