-- Supabase Table Setup for ABN Bulk Data
--
``
-- A lookup table for the different types of business entities.
-- This table will be populated from the data itself.
CREATE TABLE public.entity_types (
    code character varying(4) NOT NULL,
    description text,
    CONSTRAINT entity_types_pkey PRIMARY KEY (code)
);

COMMENT ON TABLE public.entity_types IS 'Lookup table for ABN entity types.';

-- Table 2: entities
-- The main table to store core information for each ABN.
CREATE TABLE public.entities (
    abn character varying(11) NOT NULL,
    abn_status character varying(3),
    abn_status_from_date date,
    entity_type_code character varying(4),
    legal_name text,
    asic_number character varying(9),
    gst_status character varying(3),
    gst_status_from_date date,
    state character varying(3),
    postcode character varying(10), -- Increased size for safety
    last_updated date,
    CONSTRAINT entities_pkey PRIMARY KEY (abn),
    CONSTRAINT entities_entity_type_code_fkey FOREIGN KEY (entity_type_code) REFERENCES public.entity_types (code) ON UPDATE CASCADE ON DELETE SET NULL
);

COMMENT ON TABLE public.entities IS 'Core information for each Australian Business Number (ABN).';

-- Table 3: business_names
-- Stores the one-to-many relationship for business/trading names.
CREATE TABLE public.business_names (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    abn character varying(11) NOT NULL,
    name text,
    type character varying(3),
    CONSTRAINT business_names_pkey PRIMARY KEY (id),
    CONSTRAINT business_names_abn_fkey FOREIGN KEY (abn) REFERENCES public.entities (abn) ON UPDATE CASCADE ON DELETE CASCADE
);

COMMENT ON TABLE public.business_names IS 'Stores registered business and trading names associated with an ABN.';

-- Table 4: dgr_funds
-- Stores the one-to-many relationship for Deductible Gift Recipient funds.
CREATE TABLE public.dgr_funds (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    abn character varying(11) NOT NULL,
    fund_name text,
    status_from_date date,
    CONSTRAINT dgr_funds_pkey PRIMARY KEY (id),
    CONSTRAINT dgr_funds_abn_fkey FOREIGN KEY (abn) REFERENCES public.entities (abn) ON UPDATE CASCADE ON DELETE CASCADE
);

COMMENT ON TABLE public.dgr_funds IS 'Stores Deductible Gift Recipient (DGR) funds associated with an ABN.';
