name: Deploy Frontend Applications

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # If ./.github/actions/nx-set-shas is a custom action and exists, keep as is.
      # Otherwise, comment out or provide the correct official or community action.
      # - name: Setup Nx
      #   uses: ./.github/actions/nx-set-shas

      - name: Build frontend applications
        run: pnpm exec nx build firmable-web-ui --configuration=production
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}

      # If ./.github/actions/configure-pages is a custom action and exists, keep as is.
      # Otherwise, use the official actions/configure-pages if available, or comment out.
      # - name: Setup Pages
      #   uses: actions/configure-pages@v5
      #   with:
      #     static_site_generator: next

      # If ./.github/actions/upload-pages-artifact is a custom action and exists, keep as is.
      # Otherwise, use the official actions/upload-pages-artifact if available, or comment out.
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: ./dist/apps/firmable-web-ui

      # If ./.github/actions/deploy-pages is a custom action and exists, keep as is.
      # Otherwise, use the official actions/deploy-pages if available, or comment out.
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v4
